version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            echo "This is a dummy CircleCI build job."
            python --version

workflows:
  version: 2
  test_pipeline:
    jobs:
      - build
